version: 0.1

phases:
  install: 
    commands:
      - go get -u github.com/golang/lint/golint

  pre_build:
    commands:
      - golint -set_exit_status

  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code...
      - go build -o mongosnap
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - mongosnap
    - appspec.yml