version: 0.1
            
phases:

  install: 
    commands:
      - go get -u github.com/golang/lint/golint
      - go get -u "github.com/crielly/mongosnap/logger"
	    - go get -u "github.com/rlmcpherson/s3gof3r"

  pre_build: 
    commands:
      # Ensure code passes all lint tests
      - golint -set_exit_status

  build:
    commands:

      # Build our application
      - go build -o main

artifacts:
  files:
    - mongosnap
    - buildspec.yml
