---
cluster:
  storage:
    volumeGroup: /dev/ephem_vg
    logicalVolume: ephem_lv
    fileSystem: xfs
  snapshot:
    mountPath: /backup
    opts: -onouuid,ro
    snapshotName: mongobackup
    size: 100%FREE
  replicaConfs:
    - /etc/mongodb00.conf
    - /etc/mongodb01.conf
    - /etc/mongodb02.conf

s3:
  bucket: mongo-db-backups
  objectPath: mongo-db-backups-test

