---
cluster:
  storage:
    volumeGroup: /dev/ephem_vg
    logicalVolume: ephem_lv
    fileSystem: xfs
  replicaConfs:
    - /etc/mongodb00.conf
    - /etc/mongodb01.conf
    - /etc/mongodb02.conf

s3:
  bucket: mongo-db-backups
  objectPath: mongo-db-backups-test

